export interface ICursoQ10 {
    Consecutivo: number,
    Codigo: string,
    Nombre: string,
    Codigo_docente: string,
    Abreviatura_tipo_identificacion_docente: string,
    Numero_identificacion_docente: string,
    Nombre_docente: string,
    Consecutivo_sede_jornada: number,
    Nombre_sede_jornada: string,
    Codigo_programa: string,
    Nombre_programa: string,
    Consecutivo_pensum_programa: number,
    Nombre_pensum_programa: string,
    Codigo_asignatura: string,
    Nombre_asignatura: string,
    Cupo_maximo: number,
    Cantidad_estudiantes_matriculados: number,
    Consecutivo_periodo: number,
    Nombre_periodo: string,
    Fecha_inicio: string,
    Fecha_fin: string,
    Estado: string,
    Docentes_apoyo: []
}